### ISSUE TITLE
where are the data?

### ISSUE THREAD

**Issue by yiranxijie** [luminis-ams/blog-text-classification#1]
I can not find anything about the 'data/GoogleNews-vectors-negative300.bin.gz'?

**Comment by mvanzelst** [comment]
Using the googlenews word vectors is optional, it should improve the doc2vec model. That trained word2vec model can be downloaded from: [https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing) If you place it in the data directory you should be able to use it.

**Comment by yiranxijie** [comment]
Well, thank you
